### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by narr** [narr/narr-gatsby-starter#2]
- [ ] Golang + GraphQL
- [ ] Yarn’s workspaces
- [ ] google fonts
- [ ] add links to docs pages
- [ ] check how to serve assets folder
- [ ] change/extend default mock implementation in a single test
- [ ] Links in one page e.g. tab UI
ref. with @reach/router
https://github.com/pieh/gatsby/blob/931c911c59f876639b0cfddfd5a5a1a5acc2f1b4/e2e-tests/development-runtime/src/pages/client-only-paths.js

  https://codedaily.io/tutorials/45/Create-Nested-Tab-Routes-with-Dynamic-Paths-with-React-Router
- [ ] gatsby theme
- [ ] add google analytics
- [ ] remove Lerna and update pkg.json
- [ ] check API call(proxy) and jsonp or js instead of json and Redux vs useReducer vs mobx
- [ ] check git subtree and bit.dev - common components
